# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Gradle dependencies
  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Root npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Documentation npm dependencies
  - package-ecosystem: 'npm'
    directory: '/docs'
    schedule:
      interval: 'weekly'

  # Control plane npm dependencies
  - package-ecosystem: 'npm'
    directory: '/apps/acci-eaf-control-plane'
    schedule:
      interval: 'weekly'

  # UI Foundation Kit npm dependencies
  - package-ecosystem: 'npm'
    directory: '/libs/ui-foundation-kit'
    schedule:
      interval: 'weekly'
