stages:
  - setup
  - lint
  - build
  - test
  - artifact

variables:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.caching=true'
  GRADLE_USER_HOME: '$CI_PROJECT_DIR/.gradle'
  NODE_OPTIONS: '--max_old_space_size=4096'

cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
      - package-lock.json
  paths:
    - .gradle/
    - node_modules/
    - .nx/cache/

.setup_java_node: &setup_java_node
  image: eclipse-temurin:21-jdk
  before_script:
    # Install git (required for Nx affected commands)
    - apt-get update && apt-get install -y git
    # Install Node.js
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    - apt-get install -y nodejs
    # Verify installations
    - java -version
    - node --version
    - npm --version
    - git --version
    # Install dependencies
    - npm ci
    # Make gradlew executable
    - chmod +x ./gradlew

setup:
  <<: *setup_java_node
  stage: setup
  script:
    - echo "Setup completed"

lint_backend:
  <<: *setup_java_node
  stage: lint
  script:
    - echo "Running Kotlin/Gradle formatting checks..."
    - ./gradlew spotlessCheck
  allow_failure: false

lint_frontend:
  <<: *setup_java_node
  stage: lint
  script:
    - echo "Running frontend linting and formatting checks..."
    - npx nx run-many --target=lint --all
    - npx nx run-many --target=format:check --all
  allow_failure: false

build:
  <<: *setup_java_node
  stage: build
  script:
    - echo "Building all projects..."
    - npx nx run-many --target=build --all
  artifacts:
    paths:
      - 'apps/iam-service/build/libs/*.jar'
      - 'libs/eaf-sdk/eaf-core/build/libs/*.jar'
    expire_in: 1 day

test:
  <<: *setup_java_node
  stage: test
  script:
    - echo "Running tests for all projects..."
    - npx nx run-many --target=test --all
  artifacts:
    reports:
      junit:
        - '**/build/test-results/test/*.xml'
        - '**/test-results.xml'
    paths:
      - '**/build/reports/'
    expire_in: 1 week

archive_artifacts:
  <<: *setup_java_node
  stage: artifact
  needs:
    - build
  script:
    - echo "Archiving build artifacts..."
    - find . -name "*.jar" -type f
    - find . -name "dist" -type d
  artifacts:
    paths:
      - 'apps/iam-service/build/libs/*.jar'
      - 'libs/eaf-sdk/eaf-core/build/libs/*.jar'
    expire_in: 4 weeks
  only:
    - main
