services:
  # NATS Server with JetStream enabled for EAF MVP
  nats:
    image: nats:alpine
    container_name: eaf-nats
    ports:
      # Client connections
      - '4222:4222'
      # HTTP monitoring interface
      - '8222:8222'
      # Note: Port 6222 (clustering) not exposed since it's not configured in simple config
    volumes:
      # Mount NATS configuration file
      - ./nats-server-simple.conf:/etc/nats/nats-server.conf:ro
      # Mount data directory for JetStream persistence
      - ./nats-data:/data
    command: ['--config', '/etc/nats/nats-server.conf']
    environment:
      # Optional: Enable debug logging during development
      - NATS_DEBUG=false
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --spider --quiet http://localhost:8222/healthz || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - eaf-network

  # PostgreSQL service for EAF Event Store and IAM data
  postgres:
    image: postgres:15
    container_name: eaf-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: eaf_iam
      POSTGRES_USER: eaf_user
      POSTGRES_PASSWORD: eaf_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U eaf_user -d eaf_iam']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - eaf-network

networks:
  eaf-network:
    driver: bridge
    name: eaf-network

volumes:
  postgres_data:
    driver: local
  nats_data:
    driver: local
