server:
  port: 8082

spring:
  application:
    name: ticket-management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/eaf_tickets
    username: eaf_user
    password: eaf_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Vaadin Configuration
vaadin:
  productionMode: false
  frontend:
    hotdeploy: true
  pnpm:
    enable: false
  # Disable Flow features since we're using Hilla only
  servlet:
    disable-automatic-servlet-registration: true
  react:
    enable: true
  flow:
    enable: false

# EAF Configuration
eaf:
  eventing:
    nats:
      servers:
        - 'nats://localhost:4222'
      default-tenant-id: 'default-tenant'
      connection-name: 'ticket-management-service'
      max-reconnects: -1
      reconnect-wait-ms: 2000
      connection-timeout-ms: 5000
      ping-interval-ms: 120000
      consumer:
        auto-startup: true
        default-ack-wait: 30000
        default-max-deliver: 3
        default-max-ack-pending: 1000

  event-store:
    tenant-isolation: true
    snapshot-frequency: 100

  iam:
    service-url: http://localhost:8081
    client-id: ticket-management-service
    validate-tokens: true

app:
  security:
    auth:
      # IMPORTANT: The JWT secret for stateless authentication.
      # This value SHOULD NOT be committed to version control.
      # For local development, create a file:
      # apps/ticket-management-service/config/local/application.yml
      # And add the following content, after generating a secret with 'openssl rand -base64 32':
      #
      # app:
      #   security:
      #     auth:
      #       secret: 'YOUR_GENERATED_SECRET_HERE'
      #
      secret: ''

# Logging
logging:
  level:
    com.axians.eaf: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
